### ISSUE TITLE
Object reserved keyword

### ISSUE THREAD

**Issue by fntlnz** [zendframework/zend-barcode#14]
The `object` keyword became reserved in PHP 7, this conflicts with the `Zend\Barcode\Object;`
namespace.

http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by weierophinney** [comment]
@fntlnz It doesn't. The reason is because the namespace is not `Object`, but `Zend\Barcode\Object`; our tests even pass currently on PHP 7.

Do you have a specific example demonstrating breakage?

**Comment by fntlnz** [comment]
@weierophinney  The `object` keyword does not lead to an immediate breakage (like Int, Float and String) because is not marked as reserved in the current implementations of the PHP language (PHP, HHVM etc) but has been reserved for the future use as stated by these documentes:
- PHP Documentation [here](http://php.net/manual/en/reserved.other-reserved-words.php) 

> These words cannot be used to name a class, interface or a trait. These words are also prohibited from being used in namespaces. Some of the words are reserved to enable future PHP features without breaking backward compatibility. [...followed by a table containing reserved names including object]
- PHP language specification [here](https://github.com/php/php-langspec/blob/cfdcbd2025d2a225dd9ce9cd838dc515d60ebb47/spec/09-lexical-structure.md#names)

> The following names are reserved for future use and should not be used as the names of classes, interfaces, or traits: mixed, numeric, object, and resource.

**Comment by Maks3w** [comment]
`Object` is used as _namespace_ not as class, interface or trait.

**Comment by fntlnz** [comment]
So, what's the point?

From: http://php.net/manual/en/reserved.other-reserved-words.php

> These words are also prohibited from being used in namespaces

**Comment by Maks3w** [comment]
As @weierophinney point the namespace is the whole string. PHP does not distinguish namespace parts.

Probably `namespace Object {}` may fail due the restrictions you noticed but not `Foo\<any restricted word>`

Anyway if you found a better term for name the namespace we could consider start to use it in the next minor version (preserving the old namespace for BC)

**Comment by gianarb** [comment]
Hello @fntlnz :) 

We can start to use a new name ( and mark this class as deprecated in order to remove it during 3.0 release
- Zend\Barcode\BarcodeObject
- Zend\Barcode\Barcode

**Comment by remicollet** [comment]
Minimal fix in https://github.com/zendframework/zend-barcode/pull/36

**Comment by dbarn** [comment]
Hi, we are also seeing this issue in PHP 7.2

PHP Fatal error:  Cannot use Zend\Barcode\Object as Object because 'Object' is a special class name in www/vhosts/api.content-manager/src/PhysicalLookbook/Service/PdfGenerator.php on line 26

Line 26:
use Zend\Barcode\Object;

Any help very welcome.

Thks

**Comment by froschdesign** [comment]
@dbarn 
Which version of zend-barcode do you use?

**Comment by froschdesign** [comment]
~~Fixed with #36 and released with version [2.6.1](https://github.com/zendframework/zend-barcode/releases/tag/release-2.6.1)~~

**Comment by froschdesign** [comment]
Related to #37

**Comment by dbarn** [comment]
Hi we are using 2.7
I have fixed by aliasing the object in our code:
Line 26:
use Zend\Barcode\Object as BarcodeObject

And then using 
$barcode = new Object\Ean13();

This work ok.

**Comment by froschdesign** [comment]
@dbarn 
Thanks for your feedback!

I will reopen this issue, because the problem with `Object` in namespace was not fixed and must be done on version 3.0!

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas/laminas-barcode; a new issue has been opened at https://github.com/laminas/laminas-barcode/issues/1.
